api_platform:
    title: Automação STI

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'

    defaults:
        pagination_client_items_per_page: true
