security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'

    providers:
        app_user_provider:
            memory:
                users:
                    admin:
                        # A senha é "password"
                        password: '$argon2id$v=19$m=65536,t=4,p=1$U2xMaU9TbzdESGcvdEx1UQ$8h9YFjOM6vdTke5G7/IMymi5kjOm7z7OVVXLR7yO1eQ'
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        main:
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/taiga-webhook, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
